cleverage_settings:
    path:     /configuration/admin
    controller: Ezplatform\SettingsBundle\Controller\DefaultController::indexAction

cleverage_settings_ajax_form:
    path: /configuration/admin/form
    controller: Ezplatform\SettingsBundle\Controller\DefaultController::ajaxGetFormSiteaccessAction

cleverage_settings_ajax_update:
    path: /configuration/admin/update
    controller: Ezplatform\SettingsBundle\Controller\DefaultController::ajaxUpdateAction

cleverage_settings_clear_cache:
    path: /configuration/admin/clear
    controller: Ezplatform\SettingsBundle\Controller\DefaultController::clearCacheAction