masev_settings:
    path:     /configuration/admin
    controller: Masev\SettingsBundle\Controller\DefaultController::indexAction

masev_ajax_form:
    path: /configuration/admin/form
    controller: Masev\SettingsBundle\Controller\DefaultController::ajaxGetFormSiteaccessAction

masev_ajax_update:
    path: /configuration/admin/update
    controller: Masev\SettingsBundle\Controller\DefaultController::ajaxUpdateAction

masev_clear_cache:
    path: /configuration/admin/clear
    controller: Masev\SettingsBundle\Controller\DefaultController::clearCacheAction