services:
    masev.event_listener.main_menu_builder:
        class: Masev\SettingsBundle\PlatformAdminUI\EventListener\MainMenuBuilderListener
        tags:
            - { name: kernel.event_subscriber }

    masev.form.siteaccess.type:
        class:  Masev\SettingsBundle\Form\Type\SiteaccessType
        arguments: ['@router']
        tags:
            - { name: form.type, alias: siteaccess.type }

    masev.purger:
        class:  Masev\SettingsBundle\Service\Purger
        public: true
        arguments: ['@ezplatform.http_cache.purge_client_decorator']