services:
    cleverage_settings.event_listener.main_menu_builder:
        class: Ezplatform\SettingsBundle\PlatformAdminUI\EventListener\MainMenuBuilderListener
        arguments: [ '@security.authorization_checker' ]
        tags:
            - { name: kernel.event_subscriber }

    cleverage_settings.form.siteaccess.type:
        class:  Ezplatform\SettingsBundle\Form\Type\SiteaccessType
        arguments: ['@router']
        tags:
            - { name: form.type, alias: siteaccess.type }

    cleverage_settings.purger:
        class:  Ezplatform\SettingsBundle\Service\Purger
        public: true
        arguments: ['@ezplatform.http_cache.purge_client_decorator']